export interface ProductItem {
    id: number;
    name: string;
    category: string;
    price: string;
    priceNum: number;
    img: string;
    tag: string;
    tagColor: string;
    desc: string;
    fullDesc: string;
    ingredients: string[];
    calories: string;
    prepTime: string;
    rating: number;
}

export const ALL_PRODUCTS: ProductItem[] = [
    {
        id: 1,
        name: 'Classic Lemonade',
        category: 'Beverages',
        price: '₱120',
        priceNum: 120,
        tag: 'Best Seller',
        tagColor: 'from-amber-500 to-yellow-400',
        img: '/assets/lemonade1.jpg',
        desc: 'Our original recipe, cold-pressed daily from organic tree-ripened lemons with pure sugarcane juice.',
        fullDesc: 'Crafted every morning from tree-ripened lemons sourced directly from local Batangas farms. Cold-pressed to preserve maximum vitamin C and natural flavor compounds. Sweetened purely with Philippine sugarcane juice — never refined sugar. Served over hand-cut ice with a fresh lemon wheel.',
        ingredients: ['Organic Lemon', 'Sugarcane Juice', 'Purified Water', 'Himalayan Salt'],
        calories: '95 kcal',
        prepTime: '3 min',
        rating: 4.9,
    },
    {
        id: 2,
        name: 'Honey Mint Infusion',
        category: 'Beverages',
        price: '₱140',
        priceNum: 140,
        tag: 'New',
        tagColor: 'from-emerald-500 to-teal-400',
        img: '/assets/lemonade2.jpg',
        desc: 'Wild honey blended with crushed garden mint and fresh lemon juice for a refreshing purple herbal twist.',
        fullDesc: 'A sophisticated blend of wild forest honey sourced from Bukidnon bee farms, muddled with fresh garden mint, and brightened with cold-pressed lemon juice. The stunning purple hue comes from a touch of butterfly pea flower tea — naturally caffeine-free and rich in antioxidants.',
        ingredients: ['Wild Forest Honey', 'Fresh Garden Mint', 'Lemon Juice', 'Butterfly Pea Tea'],
        calories: '110 kcal',
        prepTime: '5 min',
        rating: 4.8,
    },
    {
        id: 3,
        name: 'Citrus Ginger Fizz',
        category: 'Beverages',
        price: '₱150',
        priceNum: 150,
        tag: 'Spicy',
        tagColor: 'from-rose-500 to-orange-400',
        img: '/assets/lemonade3.jpg',
        desc: 'Zesty ginger juice, sparkling water, and red berry cold-pressed lemon juice.',
        fullDesc: 'A bold, invigorating fizz built on freshly pressed ginger root, tangy red citrus lemonade, and naturally carbonated mineral water. Topped with dried chili salt rim and a wedge of blood orange. Known to boost metabolism and settle the stomach — our go-to wellness drink.',
        ingredients: ['Fresh Ginger Root', 'Blood Orange', 'Mineral Water', 'Red Citrus', 'Chili Salt Rim'],
        calories: '85 kcal',
        prepTime: '4 min',
        rating: 4.7,
    },
    {
        id: 4,
        name: 'Chocolate Cherry Gateau',
        category: 'Pastries',
        price: '₱180',
        priceNum: 180,
        tag: 'Signature',
        tagColor: 'from-purple-500 to-pink-400',
        img: '/assets/menu2.jpg',
        desc: 'Decadent layers of rich dark cocoa cake, sweet black cherries, and fluffy whipped cream.',
        fullDesc: 'Our showstopper pastry — three layers of 70% dark cocoa sponge cake soaked in house-made Kirsch syrup, filled with Morello black cherries and lightly sweetened cream, then decorated with rosettes, fresh Bing cherries, and a generous coat of Belgian dark chocolate shavings. Made fresh daily.',
        ingredients: ['Belgian Dark Chocolate', 'Morello Cherries', 'Fresh Cream', 'Cocoa Sponge', 'Kirsch Syrup'],
        calories: '380 kcal',
        prepTime: '—',
        rating: 5.0,
    },
    {
        id: 5,
        name: 'Citrus Vinaigrette Salad',
        category: 'Appetizers',
        price: '₱280',
        priceNum: 280,
        tag: 'Popular',
        tagColor: 'from-green-500 to-lime-400',
        img: '/assets/menu3.jpg',
        desc: 'Crisp seasonal greens, cucumber, almonds, and red onions tossed in our zesty house citrus dressing.',
        fullDesc: 'A refreshing ensemble of baby arugula, butter lettuce, sliced English cucumber, toasted slivered almonds, thinly sliced red onion, and sundried cherry tomatoes — all brought together with our signature house-made citrus vinaigrette of lemon zest, extra-virgin olive oil, Dijon mustard, and a touch of honey.',
        ingredients: ['Baby Arugula', 'Butter Lettuce', 'Toasted Almonds', 'Red Onion', 'Citrus Vinaigrette'],
        calories: '210 kcal',
        prepTime: '8 min',
        rating: 4.6,
    },
    {
        id: 6,
        name: 'Kiwi Cucumber Mint Cooler',
        category: 'Appetizers',
        price: '₱350',
        priceNum: 350,
        tag: 'Chef Choice',
        tagColor: 'from-cyan-500 to-blue-400',
        img: '/assets/lemonade5.jpg',
        desc: 'Vibrant blend of fresh kiwi, cucumber slices, mint leaves, and cold-pressed lemon juice.',
        fullDesc: `Chef's personal recipe — a high-vibration wellness shot elevated into a full drink. Fresh Zespri kiwi blended smooth with English cucumber, a generous handful of spearmint, and brightened with cold-pressed Meyer lemon. Finished with a pinch of Himalayan pink salt and served in a chilled tall glass with a cucumber ribbon garnish.`,
        ingredients: ['Zespri Kiwi', 'English Cucumber', 'Spearmint', 'Meyer Lemon', 'Pink Salt'],
        calories: '130 kcal',
        prepTime: '6 min',
        rating: 4.9,
    },
    {
        id: 101,
        name: 'Honey Lemon Brew',
        category: 'Beverages',
        price: '₱160',
        priceNum: 160,
        tag: 'Staff Pick',
        tagColor: 'from-amber-500 to-orange-400',
        img: '/assets/lemonade6.jpg',
        desc: 'Richly brewed classic black tea with real squeezed lemon and organic honey.',
        fullDesc: 'Our crown jewel. Premium Ceylon black tea brewed at 90°C for exactly 4 minutes, steeped with a fresh lemon wheel, then sweetened with raw organic honey from Laguna beehives. Served warm or over ice — a timeless comfort in every sip. The brew is prepared in small batches every 2 hours to guarantee freshness.',
        ingredients: ['Ceylon Black Tea', 'Organic Honey', 'Fresh Lemon', 'Purified Water'],
        calories: '75 kcal',
        prepTime: '7 min',
        rating: 4.9,
    },
    {
        id: 102,
        name: 'Lavender Mint Infusion',
        category: 'Beverages',
        price: '₱175',
        priceNum: 175,
        tag: 'Aromatic',
        tagColor: 'from-violet-500 to-purple-400',
        img: '/assets/lemonade2.jpg',
        desc: 'A magical blend of organic lavender flowers, garden mint, and fresh lemon juice.',
        fullDesc: 'Inspired by the fields of Provence, this caffeine-free botanical infusion steeps food-grade organic lavender buds with freshly picked mint leaves from our rooftop garden. Combined with a bright squeeze of fresh lemon and a touch of wildflower honey, it calms the mind while delighting the palate. A true sensory experience.',
        ingredients: ['Organic Lavender', 'Fresh Mint', 'Lemon Juice', 'Wildflower Honey'],
        calories: '60 kcal',
        prepTime: '5 min',
        rating: 4.8,
    },
    {
        id: 103,
        name: 'Red Berry Citrus Splash',
        category: 'Beverages',
        price: '₱155',
        priceNum: 155,
        tag: 'Vibrant',
        tagColor: 'from-rose-500 to-pink-400',
        img: '/assets/lemonade3.jpg',
        desc: 'Refreshing sweet-tart hibiscus tea mixed with fresh lemon and wild honey.',
        fullDesc: 'Dried hibiscus flowers cold-brewed for 12 hours produce a deep ruby-red liquid packed with Vitamin C and antioxidants. We blend this with freshly pressed lemon juice, a hint of wild honey, and a splash of sparkling water. Gorgeous in color and bold in flavor — the ultimate refresher on a hot day.',
        ingredients: ['Hibiscus Flowers', 'Fresh Lemon', 'Wild Honey', 'Sparkling Water'],
        calories: '90 kcal',
        prepTime: '4 min',
        rating: 4.7,
    },
    {
        id: 104,
        name: 'Cucumber Mint Squeeze',
        category: 'Beverages',
        price: '₱145',
        priceNum: 145,
        tag: 'Wellness',
        tagColor: 'from-emerald-500 to-green-400',
        img: '/assets/lemonade5.jpg',
        desc: 'Refreshing green cooler blended with fresh cucumber, mint leaves, and lime juice.',
        fullDesc: 'Our wellness signature — a cold-pressed juice built from whole English cucumbers, a generous handful of spearmint leaves, the juice of two limes, and a pinch of Himalayan pink salt for electrolytes. Dairy-free, refined sugar-free, and naturally hydrating. Packed with silica, chlorophyll, and vitamins B & C. Served in a chilled glass with a cucumber ribbon and mint sprig.',
        ingredients: ['English Cucumber', 'Spearmint', 'Lime Juice', 'Pink Salt'],
        calories: '55 kcal',
        prepTime: '5 min',
        rating: 4.9,
    }
];

export const MENU_ITEMS = ALL_PRODUCTS.filter(p => p.id < 100);
export const SPECIALTIES = ALL_PRODUCTS.filter(p => p.id >= 100);
